version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: shopnow-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--bind_ip_all"]
    networks:
      - shopnow-net

  backend:
    image: adish786/backend:secure
    container_name: shopnow-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/shopnow
      PORT: 5000
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      shopnow-net:
        aliases:
          - backend-service

  frontend:
    image: adish786/frontend:latest
    container_name: shopnow-frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - shopnow-net

  admin:
    image: adish786/admin:latest
    container_name: shopnow-admin
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - shopnow-net

networks:
  shopnow-net:
    driver: bridge

volumes:
  mongo-data:
