apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
{{ if .Values.secret.enabled }}
type: Opaque
stringData:
  MONGODB_URI: "{{ .Values.secret.MONGODB_URI }}"
{{ end }}
