name: Backend Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: adish786/backend:secure
  TRIVY_SEVERITY: HIGH,CRITICAL
  TRIVY_EXIT_CODE: 1

jobs:
  trivy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
          docker build \
            -t $IMAGE_NAME \
            -f backend/Dockerfile \
            backend

      - name: Trivy Scan (Fail on High/Critical)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          severity: ${{ env.TRIVY_SEVERITY }}
          exit-code: ${{ env.TRIVY_EXIT_CODE }}
          ignore-unfixed: true
