name: Container Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: adish786/backend:secure
  TRIVY_SEVERITY: HIGH,CRITICAL
  TRIVY_EXIT_CODE: 1

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          severity: ${{ env.TRIVY_SEVERITY }}
          exit-code: ${{ env.TRIVY_EXIT_CODE }}
          format: table
          ignore-unfixed: true

      - name: Push Image (Only if Scan Passes)
        if: success()
        run: docker push $IMAGE_NAME
